
services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: vibrato
      POSTGRES_PASSWORD: blueprotocol
      POSTGRES_DB: vibrato
    ports:
      - "2222:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  app:
    build: .
    container_name: spring-app
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/vibrato
      SPRING_DATASOURCE_USERNAME: vibrato
      SPRING_DATASOURCE_PASSWORD: blueprotocol
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

volumes:
  pgdata:
